### ISSUE TITLE
Missing all plugins on latest docker image

### ISSUE THREAD

**Issue by stepanovdg** [Unmanic/unmanic#509]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Yes
Remember that these are some guidelines, use your best judgement.

### Description

Docker compose - running image - no plugins.

### Steps to Reproduce

1. Empty config. New install. 
2. Got to plugins -> no plugins and not possible to add official repo. Nothing in the logs (unmanic.log)
3. Tried to add repo url -> https://raw.githubusercontent.com/Unmanic/unmanic-plugins/refs/heads/repo/repo.json

**Expected behavior:** [What you expect to happen]
List of plugins, or posibility to add repo to install them.
**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always.
### Versions
Version: [0.2.8+925008e+dirty](https://github.com/unmanic/unmanic/releases)

### Installation Method Used
docker compose:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888 # Unmanic
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    # - NVIDIA_VISIBLE_DEVICES=<NVIDIA_VISIBLE_DEVICES>
    volumes:
      - ${CONFIG_DIR}/unmanic:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR}/media/transcode:/tmp/unmanic
    #runtime: nvidia       # For H/W transcoding using the NVENC encoder
    restart: unless-stopped
Manually installed and run or run through Docker?
Docker.
### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.
![Screenshot 2024-10-30 at 14 23 22](https://github.com/user-attachments/assets/330742bc-bc8a-4035-ba7e-766794bfc9f5)
![Screenshot 2024-10-30 at 14 28 43](https://github.com/user-attachments/assets/6ae7ec8d-e8ac-4b25-9e93-81086067e93e)
![Screenshot 2024-10-30 at 14 29 24](https://github.com/user-attachments/assets/104d1336-e519-43c6-8e3b-58c305c51761)

```
2024-10-30T10:47:09:INFO:Unmanic.UnmanicLogger - Debug logging disabled
2024-10-30T10:47:09:INFO:Unmanic.Migrations - Initialising database tables
2024-10-30T10:47:09:INFO:Unmanic.Migrations - Starting migrations
2024-10-30T10:47:09:INFO:Unmanic.Migrations - Migrate "001_rename_ffmpeg_log_to_log"
2024-10-30T10:47:09:INFO:Unmanic.Migrations - Done 001_rename_ffmpeg_log_to_log
2024-10-30T10:47:09:INFO:Unmanic.Migrations - Updating database fields
2024-10-30T10:47:09:INFO:Unmanic - Clearing previous cache
2024-10-30T10:47:09:INFO:Unmanic - Starting all threads
2024-10-30T10:47:09:INFO:Unmanic.Session - Initialising new session object
2024-10-30T10:47:42:INFO:Unmanic - Starting PostProcessor
2024-10-30T10:47:42:INFO:Unmanic.PostProcessor - [FORMATTED] - Starting PostProcessor Monitor loop...
2024-10-30T10:47:42:INFO:Unmanic - Starting Foreman
2024-10-30T10:47:42:INFO:Unmanic.Foreman - [FORMATTED] - Starting Foreman Monitor loop
2024-10-30T10:47:42:INFO:Unmanic - Starting TaskHandler
2024-10-30T10:47:42:INFO:Unmanic.TaskHandler - [FORMATTED] - Starting TaskHandler Monitor loop
2024-10-30T10:47:42:INFO:Unmanic - Starting LibraryScannerManager
2024-10-30T10:47:42:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Starting LibraryScanner Monitor loop
2024-10-30T10:47:42:INFO:Unmanic - Starting EventMonitorManager
2024-10-30T10:47:42:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Starting EventMonitorManager loop
2024-10-30T10:47:42:INFO:Unmanic - Starting UIServer
2024-10-30T10:47:42:INFO:Unmanic - Starting ScheduledTasksManager
2024-10-30T10:47:42:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Starting ScheduledTasks Monitor loop
2024-10-30T10:47:43:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Setting LibraryScanner schedule to scan every 1440 mins...
2024-10-30T11:47:44:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Updating session data
2024-10-30T11:47:45:INFO:Unmanic.Session - Failed to check in with Unmanic support auth API.
2024-10-30T11:47:45:INFO:Unmanic.Session - Remote Message: Malformed request to get token.
2024-10-30T12:44:05:INFO:Unmanic.default-Worker-1 - [FORMATTED] - Starting worker
2024-10-30T12:47:49:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Updating session data
2024-10-30T12:48:26:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Adding library path to monitor '/data/media/movies'
2024-10-30T12:48:27:INFO:Unmanic.EventMonitorManager - [FORMATTED] - EventMonitorManager spawning EventProcessor thread...
2024-10-30T12:55:32:INFO:Unmanic.default-Worker-1 - [FORMATTED] - Stopping worker
2024-10-30T12:55:33:INFO:Unmanic.default-Worker-1 - [FORMATTED] - Starting worker
2024-10-30T12:55:47:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Running full library scan on library '| 2 | New Library (lwoqu)'
2024-10-30T12:55:47:INFO:Unmanic.FileTesterThread-0 - [FORMATTED] - Starting FileTesterThread-0
2024-10-30T12:55:47:INFO:Unmanic.FileTesterThread-1 - [FORMATTED] - Starting FileTesterThread-1
2024-10-30T12:55:54:INFO:Unmanic.FileTesterThread-1 - [FORMATTED] - Exiting FileTesterThread-1
2024-10-30T12:55:54:INFO:Unmanic.FileTesterThread-0 - [FORMATTED] - Exiting FileTesterThread-0
2024-10-30T12:55:54:WARNING:Unmanic.LibraryScannerManager - [FORMATTED] - Library scan completed in 6.764322996139526 seconds
2024-10-30T12:55:55:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Setting LibraryScanner schedule to scan every 1440 mins...
2024-10-30T13:15:39:INFO:Unmanic - Received 15
2024-10-30T13:15:39:INFO:Unmanic - Stopping all threads
2024-10-30T13:15:39:INFO:Unmanic - Sending thread PostProcessor abort signal
2024-10-30T13:15:39:INFO:Unmanic - Sending thread Foreman abort signal
2024-10-30T13:15:39:INFO:Unmanic - Sending thread TaskHandler abort signal
2024-10-30T13:15:39:INFO:Unmanic - Sending thread LibraryScannerManager abort signal
2024-10-30T13:15:39:INFO:Unmanic - Sending thread EventMonitorManager abort signal
2024-10-30T13:15:39:INFO:Unmanic - Sending thread UIServer abort signal
2024-10-30T13:15:39:INFO:Unmanic - Sending thread ScheduledTasksManager abort signal
2024-10-30T13:15:39:INFO:Unmanic - Waiting for thread PostProcessor to stop
2024-10-30T13:15:39:INFO:Unmanic.default-Worker-1 - [FORMATTED] - Stopping worker
2024-10-30T13:15:39:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Leaving ScheduledTasks Monitor loop...
2024-10-30T13:15:39:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Leaving LibraryScanner Monitor loop...
2024-10-30T13:15:39:INFO:Unmanic.PostProcessor - [FORMATTED] - Leaving PostProcessor Monitor loop...
2024-10-30T13:15:39:INFO:Unmanic.UIServer - [FORMATTED] - Leaving UIServer loop...
2024-10-30T13:15:39:INFO:Unmanic - Thread PostProcessor has successfully stopped
2024-10-30T13:15:39:INFO:Unmanic - Waiting for thread Foreman to stop
2024-10-30T13:15:39:INFO:Unmanic.TaskHandler - [FORMATTED] - Leaving TaskHandler Monitor loop...
2024-10-30T13:15:39:INFO:Unmanic.EventMonitorManager - [FORMATTED] - EventMonitorManager stopping EventProcessor thread...
2024-10-30T13:15:39:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Sending thread EventProcessor abort signal
2024-10-30T13:15:40:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Waiting for thread EventProcessor to stop
2024-10-30T13:15:40:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Thread EventProcessor has successfully stopped
2024-10-30T13:15:40:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Leaving EventMonitorManager loop...
2024-10-30T13:15:40:INFO:Unmanic.Foreman - [FORMATTED] - Leaving Foreman Monitor loop...
2024-10-30T13:15:40:INFO:Unmanic - Thread Foreman has successfully stopped
2024-10-30T13:15:40:INFO:Unmanic - Waiting for thread TaskHandler to stop
2024-10-30T13:15:40:INFO:Unmanic - Thread TaskHandler has successfully stopped
2024-10-30T13:15:40:INFO:Unmanic - Waiting for thread LibraryScannerManager to stop
2024-10-30T13:15:40:INFO:Unmanic - Thread LibraryScannerManager has successfully stopped
2024-10-30T13:15:40:INFO:Unmanic - Waiting for thread EventMonitorManager to stop
2024-10-30T13:15:40:INFO:Unmanic - Thread EventMonitorManager has successfully stopped
2024-10-30T13:15:40:INFO:Unmanic - Waiting for thread UIServer to stop
2024-10-30T13:15:40:INFO:Unmanic - Thread UIServer has successfully stopped
2024-10-30T13:15:40:INFO:Unmanic - Waiting for thread ScheduledTasksManager to stop
2024-10-30T13:15:40:INFO:Unmanic - Thread ScheduledTasksManager has successfully stopped
2024-10-30T13:15:40:INFO:Unmanic - Exit Unmanic
2024-10-30T13:15:54:INFO:Unmanic.UnmanicLogger - Debug logging disabled
2024-10-30T13:15:54:INFO:Unmanic.Migrations - Initialising database tables
2024-10-30T13:15:54:INFO:Unmanic.Migrations - Starting migrations
2024-10-30T13:15:54:INFO:Unmanic.Migrations - There is nothing to migrate
2024-10-30T13:15:54:INFO:Unmanic.Migrations - Updating database fields
2024-10-30T13:15:54:INFO:Unmanic - Clearing previous cache
2024-10-30T13:15:54:INFO:Unmanic - Starting all threads
2024-10-30T13:15:54:INFO:Unmanic.Session - Initialising new session object
2024-10-30T13:16:26:INFO:Unmanic - Starting PostProcessor
2024-10-30T13:16:26:INFO:Unmanic.PostProcessor - [FORMATTED] - Starting PostProcessor Monitor loop...
2024-10-30T13:16:26:INFO:Unmanic - Starting Foreman
2024-10-30T13:16:26:INFO:Unmanic.Foreman - [FORMATTED] - Starting Foreman Monitor loop
2024-10-30T13:16:26:INFO:Unmanic - Starting TaskHandler
2024-10-30T13:16:26:INFO:Unmanic.TaskHandler - [FORMATTED] - Starting TaskHandler Monitor loop
2024-10-30T13:16:26:INFO:Unmanic - Starting LibraryScannerManager
2024-10-30T13:16:26:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Starting LibraryScanner Monitor loop
2024-10-30T13:16:26:INFO:Unmanic - Starting EventMonitorManager
2024-10-30T13:16:26:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Starting EventMonitorManager loop
2024-10-30T13:16:26:INFO:Unmanic - Starting UIServer
2024-10-30T13:16:26:INFO:Unmanic - Starting ScheduledTasksManager
2024-10-30T13:16:26:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Starting ScheduledTasks Monitor loop
2024-10-30T13:16:26:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Running completed task cleanup for this installation
2024-10-30T13:16:27:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Found no successfully completed tasks older than 91 days
2024-10-30T13:16:28:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Setting LibraryScanner schedule to scan every 1440 mins...
2024-10-30T13:16:28:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Running LibraryScanner on start
2024-10-30T13:16:28:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Adding library path to monitor '/data/media/movies'
2024-10-30T13:16:28:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Running full library scan on library '| 2 | New Library (lwoqu)'
2024-10-30T13:16:28:INFO:Unmanic.FileTesterThread-0 - [FORMATTED] - Starting FileTesterThread-0
2024-10-30T13:16:28:INFO:Unmanic.FileTesterThread-1 - [FORMATTED] - Starting FileTesterThread-1
2024-10-30T13:16:28:INFO:Unmanic.default-Worker-1 - [FORMATTED] - Starting worker
2024-10-30T13:16:29:INFO:Unmanic.EventMonitorManager - [FORMATTED] - EventMonitorManager spawning EventProcessor thread...
2024-10-30T13:16:34:INFO:Unmanic.FileTesterThread-0 - [FORMATTED] - Exiting FileTesterThread-0
2024-10-30T13:16:34:INFO:Unmanic.FileTesterThread-1 - [FORMATTED] - Exiting FileTesterThread-1
2024-10-30T13:16:34:WARNING:Unmanic.LibraryScannerManager - [FORMATTED] - Library scan completed in 6.559368133544922 seconds
2024-10-30T13:28:15:INFO:Unmanic - Received 15
2024-10-30T13:28:15:INFO:Unmanic - Stopping all threads
2024-10-30T13:28:15:INFO:Unmanic - Sending thread PostProcessor abort signal
2024-10-30T13:28:15:INFO:Unmanic - Sending thread Foreman abort signal
2024-10-30T13:28:15:INFO:Unmanic - Sending thread TaskHandler abort signal
2024-10-30T13:28:15:INFO:Unmanic - Sending thread LibraryScannerManager abort signal
2024-10-30T13:28:15:INFO:Unmanic - Sending thread EventMonitorManager abort signal
2024-10-30T13:28:15:INFO:Unmanic - Sending thread UIServer abort signal
2024-10-30T13:28:15:INFO:Unmanic - Sending thread ScheduledTasksManager abort signal
2024-10-30T13:28:15:INFO:Unmanic - Waiting for thread PostProcessor to stop
2024-10-30T13:28:15:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Leaving ScheduledTasks Monitor loop...
2024-10-30T13:28:15:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Leaving LibraryScanner Monitor loop...
2024-10-30T13:28:15:INFO:Unmanic.default-Worker-1 - [FORMATTED] - Stopping worker
2024-10-30T13:28:15:INFO:Unmanic.TaskHandler - [FORMATTED] - Leaving TaskHandler Monitor loop...
2024-10-30T13:28:15:INFO:Unmanic.UIServer - [FORMATTED] - Leaving UIServer loop...
2024-10-30T13:28:15:INFO:Unmanic.PostProcessor - [FORMATTED] - Leaving PostProcessor Monitor loop...
2024-10-30T13:28:15:INFO:Unmanic - Thread PostProcessor has successfully stopped
2024-10-30T13:28:15:INFO:Unmanic - Waiting for thread Foreman to stop
2024-10-30T13:28:16:INFO:Unmanic.EventMonitorManager - [FORMATTED] - EventMonitorManager stopping EventProcessor thread...
2024-10-30T13:28:16:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Sending thread EventProcessor abort signal
2024-10-30T13:28:16:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Waiting for thread EventProcessor to stop
2024-10-30T13:28:16:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Thread EventProcessor has successfully stopped
2024-10-30T13:28:16:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Leaving EventMonitorManager loop...
2024-10-30T13:28:16:INFO:Unmanic.Foreman - [FORMATTED] - Leaving Foreman Monitor loop...
2024-10-30T13:28:16:INFO:Unmanic - Thread Foreman has successfully stopped
2024-10-30T13:28:16:INFO:Unmanic - Waiting for thread TaskHandler to stop
2024-10-30T13:28:16:INFO:Unmanic - Thread TaskHandler has successfully stopped
2024-10-30T13:28:16:INFO:Unmanic - Waiting for thread LibraryScannerManager to stop
2024-10-30T13:28:16:INFO:Unmanic - Thread LibraryScannerManager has successfully stopped
2024-10-30T13:28:16:INFO:Unmanic - Waiting for thread EventMonitorManager to stop
2024-10-30T13:28:16:INFO:Unmanic - Thread EventMonitorManager has successfully stopped
2024-10-30T13:28:16:INFO:Unmanic - Waiting for thread UIServer to stop
2024-10-30T13:28:16:INFO:Unmanic - Thread UIServer has successfully stopped
2024-10-30T13:28:16:INFO:Unmanic - Waiting for thread ScheduledTasksManager to stop
2024-10-30T13:28:16:INFO:Unmanic - Thread ScheduledTasksManager has successfully stopped
2024-10-30T13:28:16:INFO:Unmanic - Exit Unmanic
2024-10-30T13:28:45:INFO:Unmanic.UnmanicLogger - Debug logging disabled
2024-10-30T13:28:45:INFO:Unmanic.Migrations - Initialising database tables
2024-10-30T13:28:45:INFO:Unmanic.Migrations - Starting migrations
2024-10-30T13:28:45:INFO:Unmanic.Migrations - There is nothing to migrate
2024-10-30T13:28:45:INFO:Unmanic.Migrations - Updating database fields
2024-10-30T13:28:45:INFO:Unmanic - Clearing previous cache
2024-10-30T13:28:45:INFO:Unmanic - Starting all threads
2024-10-30T13:28:45:INFO:Unmanic.Session - Initialising new session object
2024-10-30T13:29:17:INFO:Unmanic - Starting PostProcessor
2024-10-30T13:29:17:INFO:Unmanic.PostProcessor - [FORMATTED] - Starting PostProcessor Monitor loop...
2024-10-30T13:29:17:INFO:Unmanic - Starting Foreman
2024-10-30T13:29:18:INFO:Unmanic.Foreman - [FORMATTED] - Starting Foreman Monitor loop
2024-10-30T13:29:18:INFO:Unmanic - Starting TaskHandler
2024-10-30T13:29:18:INFO:Unmanic.TaskHandler - [FORMATTED] - Starting TaskHandler Monitor loop
2024-10-30T13:29:18:INFO:Unmanic - Starting LibraryScannerManager
2024-10-30T13:29:18:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Starting LibraryScanner Monitor loop
2024-10-30T13:29:18:INFO:Unmanic - Starting EventMonitorManager
2024-10-30T13:29:18:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Starting EventMonitorManager loop
2024-10-30T13:29:18:INFO:Unmanic - Starting UIServer
2024-10-30T13:29:18:INFO:Unmanic - Starting ScheduledTasksManager
2024-10-30T13:29:18:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Starting ScheduledTasks Monitor loop
2024-10-30T13:29:18:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Running completed task cleanup for this installation
2024-10-30T13:29:18:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Found no successfully completed tasks older than 91 days
2024-10-30T13:29:19:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Setting LibraryScanner schedule to scan every 1440 mins...
2024-10-30T13:29:19:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Running LibraryScanner on start
2024-10-30T13:29:19:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Adding library path to monitor '/data/media/movies'
2024-10-30T13:29:19:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Running full library scan on library '| 2 | New Library (lwoqu)'
2024-10-30T13:29:19:INFO:Unmanic.FileTesterThread-0 - [FORMATTED] - Starting FileTesterThread-0
2024-10-30T13:29:19:INFO:Unmanic.FileTesterThread-1 - [FORMATTED] - Starting FileTesterThread-1
2024-10-30T13:29:20:INFO:Unmanic.default-Worker-1 - [FORMATTED] - Starting worker
2024-10-30T13:29:20:INFO:Unmanic.EventMonitorManager - [FORMATTED] - EventMonitorManager spawning EventProcessor thread...
2024-10-30T13:29:25:INFO:Unmanic.FileTesterThread-0 - [FORMATTED] - Exiting FileTesterThread-0
2024-10-30T13:29:25:INFO:Unmanic.FileTesterThread-1 - [FORMATTED] - Exiting FileTesterThread-1
2024-10-30T13:29:25:WARNING:Unmanic.LibraryScannerManager - [FORMATTED] - Library scan completed in 6.5377137660980225 seconds
2024-10-30T14:04:17:INFO:Unmanic.UnmanicLogger - Debug logging disabled
2024-10-30T14:04:17:INFO:Unmanic.Migrations - Initialising database tables
2024-10-30T14:04:17:INFO:Unmanic.Migrations - Starting migrations
2024-10-30T14:04:17:INFO:Unmanic.Migrations - There is nothing to migrate
2024-10-30T14:04:17:INFO:Unmanic.Migrations - Updating database fields
2024-10-30T14:04:41:INFO:Unmanic.UnmanicLogger - Debug logging disabled
2024-10-30T14:04:41:INFO:Unmanic.Migrations - Initialising database tables
2024-10-30T14:04:41:INFO:Unmanic.Migrations - Starting migrations
2024-10-30T14:04:41:INFO:Unmanic.Migrations - There is nothing to migrate
2024-10-30T14:04:41:INFO:Unmanic.Migrations - Updating database fields
2024-10-30T14:16:13:INFO:Unmanic - Received 15
2024-10-30T14:16:13:INFO:Unmanic - Stopping all threads
2024-10-30T14:16:13:INFO:Unmanic - Sending thread PostProcessor abort signal
2024-10-30T14:16:13:INFO:Unmanic - Sending thread Foreman abort signal
2024-10-30T14:16:13:INFO:Unmanic - Sending thread TaskHandler abort signal
2024-10-30T14:16:13:INFO:Unmanic - Sending thread LibraryScannerManager abort signal
2024-10-30T14:16:13:INFO:Unmanic - Sending thread EventMonitorManager abort signal
2024-10-30T14:16:13:INFO:Unmanic - Sending thread UIServer abort signal
2024-10-30T14:16:13:INFO:Unmanic - Sending thread ScheduledTasksManager abort signal
2024-10-30T14:16:13:INFO:Unmanic - Waiting for thread PostProcessor to stop
2024-10-30T14:16:13:INFO:Unmanic.TaskHandler - [FORMATTED] - Leaving TaskHandler Monitor loop...
2024-10-30T14:16:13:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Leaving ScheduledTasks Monitor loop...
2024-10-30T14:16:13:INFO:Unmanic.EventMonitorManager - [FORMATTED] - EventMonitorManager stopping EventProcessor thread...
2024-10-30T14:16:13:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Sending thread EventProcessor abort signal
2024-10-30T14:16:13:INFO:Unmanic.default-Worker-1 - [FORMATTED] - Stopping worker
2024-10-30T14:16:13:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Leaving LibraryScanner Monitor loop...
2024-10-30T14:16:13:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Waiting for thread EventProcessor to stop
2024-10-30T14:16:13:INFO:Unmanic.UIServer - [FORMATTED] - Leaving UIServer loop...
2024-10-30T14:16:13:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Thread EventProcessor has successfully stopped
2024-10-30T14:16:13:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Leaving EventMonitorManager loop...
2024-10-30T14:16:13:INFO:Unmanic.PostProcessor - [FORMATTED] - Leaving PostProcessor Monitor loop...
2024-10-30T14:16:13:INFO:Unmanic - Thread PostProcessor has successfully stopped
2024-10-30T14:16:13:INFO:Unmanic - Waiting for thread Foreman to stop
2024-10-30T14:16:14:INFO:Unmanic.Foreman - [FORMATTED] - Leaving Foreman Monitor loop...
2024-10-30T14:16:14:INFO:Unmanic - Thread Foreman has successfully stopped
2024-10-30T14:16:14:INFO:Unmanic - Waiting for thread TaskHandler to stop
2024-10-30T14:16:14:INFO:Unmanic - Thread TaskHandler has successfully stopped
2024-10-30T14:16:14:INFO:Unmanic - Waiting for thread LibraryScannerManager to stop
2024-10-30T14:16:14:INFO:Unmanic - Thread LibraryScannerManager has successfully stopped
2024-10-30T14:16:14:INFO:Unmanic - Waiting for thread EventMonitorManager to stop
2024-10-30T14:16:14:INFO:Unmanic - Thread EventMonitorManager has successfully stopped
2024-10-30T14:16:14:INFO:Unmanic - Waiting for thread UIServer to stop
2024-10-30T14:16:14:INFO:Unmanic - Thread UIServer has successfully stopped
2024-10-30T14:16:14:INFO:Unmanic - Waiting for thread ScheduledTasksManager to stop
2024-10-30T14:16:14:INFO:Unmanic - Thread ScheduledTasksManager has successfully stopped
2024-10-30T14:16:14:INFO:Unmanic - Exit Unmanic
2024-10-30T14:16:53:INFO:Unmanic.UnmanicLogger - Debug logging disabled
2024-10-30T14:16:53:INFO:Unmanic.Migrations - Initialising database tables
2024-10-30T14:16:53:INFO:Unmanic.Migrations - Starting migrations
2024-10-30T14:16:53:INFO:Unmanic.Migrations - There is nothing to migrate
2024-10-30T14:16:53:INFO:Unmanic.Migrations - Updating database fields
2024-10-30T14:16:53:INFO:Unmanic - Clearing previous cache
2024-10-30T14:16:53:INFO:Unmanic - Starting all threads
2024-10-30T14:16:53:INFO:Unmanic.Session - Initialising new session object
2024-10-30T14:17:25:INFO:Unmanic - Starting PostProcessor
2024-10-30T14:17:25:INFO:Unmanic.PostProcessor - [FORMATTED] - Starting PostProcessor Monitor loop...
2024-10-30T14:17:25:INFO:Unmanic - Starting Foreman
2024-10-30T14:17:26:INFO:Unmanic.Foreman - [FORMATTED] - Starting Foreman Monitor loop
2024-10-30T14:17:26:INFO:Unmanic - Starting TaskHandler
2024-10-30T14:17:26:INFO:Unmanic.TaskHandler - [FORMATTED] - Starting TaskHandler Monitor loop
2024-10-30T14:17:26:INFO:Unmanic - Starting LibraryScannerManager
2024-10-30T14:17:26:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Starting LibraryScanner Monitor loop
2024-10-30T14:17:26:INFO:Unmanic - Starting EventMonitorManager
2024-10-30T14:17:26:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Starting EventMonitorManager loop
2024-10-30T14:17:26:INFO:Unmanic - Starting UIServer
2024-10-30T14:17:26:INFO:Unmanic - Starting ScheduledTasksManager
2024-10-30T14:17:26:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Starting ScheduledTasks Monitor loop
2024-10-30T14:17:26:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Running completed task cleanup for this installation
2024-10-30T14:17:26:INFO:Unmanic.ScheduledTasksManager - [FORMATTED] - Found no successfully completed tasks older than 91 days
2024-10-30T14:17:27:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Setting LibraryScanner schedule to scan every 1440 mins...
2024-10-30T14:17:27:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Running LibraryScanner on start
2024-10-30T14:17:27:INFO:Unmanic.EventMonitorManager - [FORMATTED] - Adding library path to monitor '/data/media/movies'
2024-10-30T14:17:27:INFO:Unmanic.LibraryScannerManager - [FORMATTED] - Running full library scan on library '| 2 | New Library (lwoqu)'
2024-10-30T14:17:27:INFO:Unmanic.FileTesterThread-0 - [FORMATTED] - Starting FileTesterThread-0
2024-10-30T14:17:27:INFO:Unmanic.FileTesterThread-1 - [FORMATTED] - Starting FileTesterThread-1
2024-10-30T14:17:28:INFO:Unmanic.default-Worker-1 - [FORMATTED] - Starting worker
2024-10-30T14:17:28:INFO:Unmanic.EventMonitorManager - [FORMATTED] - EventMonitorManager spawning EventProcessor thread...
2024-10-30T14:17:33:INFO:Unmanic.FileTesterThread-0 - [FORMATTED] - Exiting FileTesterThread-0
2024-10-30T14:17:33:INFO:Unmanic.FileTesterThread-1 - [FORMATTED] - Exiting FileTesterThread-1
2024-10-30T14:17:33:WARNING:Unmanic.LibraryScannerManager - [FORMATTED] - Library scan completed in 6.54681658744812 seconds

```

**Comment by patrykwegrzyn** [comment]
Same issue here , i get this in network tab in dev tools
`500: HTTPSConnectionPool(host='api.unmanic.app', port=443): Max retries exceeded with url: /unmanic-api/v1/plugin_repos/get_repo_data/uuid/963695c4-059e-47d7-b6d3-d8044ee74c49/level/0/repo/ZGVmYXVsdA== (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x73b81ee8d630>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by Josh5** [comment]
Which blacklist is this? Is it just your own personal one or a community maintained list?

**Comment by patrykwegrzyn** [comment]
not sure all i can see is 
`api.unmanic.app (blocked support-api.streamingtech.co.nz) Blocked (regex blacklist, CNAME) `
 but i can't see anything related to `api.unmanic.app` or `streamingtech.co.nz` in my config

**Comment by lfilho** [comment]
Same here on a fresh installation today. But it seems to be a 404:

![CleanShot 2024-11-20 at 14 40 01](https://github.com/user-attachments/assets/77319325-8e98-415d-a94f-873b7b77f2f9)

Got that after installing, having a blank plugins page and trying to manually save `https://raw.githubusercontent.com/Unmanic/unmanic-plugins/refs/heads/repo/repo.json` as new a repo

**Comment by nsenica** [comment]
Having the exact same problem, calls to api.unmanic.app always return a 404. 

Any work around for this issue ?

**Comment by joeltuckwell** [comment]
![Image](https://github.com/user-attachments/assets/7cc8e2a0-0be5-4b00-8761-d992fcbd40c5)

I am getting this same image after pulling down the image onto my Unraid today. Was anyone able to find a fix for this issue? Even trying to add custom repos is failing.

**Comment by Geekmeleon** [comment]
I am having the same issue with the repository being added with the latest, staging, 0.2.7, 0.2.4 images

**Comment by JCPennell** [comment]
Same deal for me. I installed from unraid and even copied the plugins over from the working unmanic install on my other unraid server and still no dice.

**Comment by Josh5** [comment]
Fixed again.

**Comment by JCPennell** [comment]
Works like a charm! Thanks @Josh5!

**Comment by jawz101** [comment]
I'm getting the same thing today

**Comment by Josh5** [comment]
> I'm getting the same thing today

Is it still happening after a restart of unmanic and a manual refresh of the repos?

**Comment by jawz101** [comment]
Yes.  for what it's worth, I tried reinstalling the docker instance completely and the issue persists.


I then tried creating a Ubuntu vm and installing unmanic in it via the python3 install instructions and that did sucessfully load plugins- however the docker image install method still had no plugins come up when I went to search for new plugins.

I would use the vm+python instance however I don't have much ram on that computer to use it inside of a virtual machine.  So it seems like it is just the docker image having probs.

... when you say 'restart unmanic' do you mean some restart command on the unmanic web portal or just restarting the docker instance altogether?  Because I tried just restarting the docker instance - though I didn't see a restart option on the web portal itself.

**Comment by jawz101** [comment]
.... it also looks like the docker container itself simply does not have network connectivity.  I set up the container with a bridged connection just like my jellyfin instance.  I don't know if that is a problem.  Anyways, when I go to the unmanic web portal , not only does the plugins repo not get data but the Account: login page will not generate a code for the Streaming Tech page.  It just sits there with a little progress circle rotating likes it's trying to generate a code.

**Comment by jawz101** [comment]
crap... @Josh5  it was me.  I have a ugreen nas & had set up its firewall to allow all connections on my LAN to it.  For some reason their firewall itself does something to screw with its own docker containers network connectivity.  Once I turned off the firewall everything works.  Sorry about that
